config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  secret_goal :boolean          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Goal < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create #logging in
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user && !logged_in
      login(user)
      redirect_to user_url(user)
    end
  end

  def new #show the login page
    render :new
  end

  def destroy #logging out
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_session_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def new
    render :new
  end

  def show
    user = User.find_by(id: params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accomplished</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <%if logged_in%>
      <form class="" action="<%=session_url%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Log out">
      </form>
    <%end%>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create user page</h1>

<%if flash[:errors]%>
  <%=flash[:errors]%>
<%end%>

<form class="" action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>
    Username:
    <input type="text" name="user[username]" value="">
  </label>
  <br>
  <label>
    Password:
    <input type="text" name="user[password]" value="">
  </label>
  <br>

  <input type="submit" name="" value="Create user!">
</form>

app/views/users/show.html.erb
<h1> Welcome, <%=current_user.username%> </h1>